"""baseline schema

Revision ID: 20260729_0001
Revises: 
Create Date: 2026-07-29 11:48:58.380133
"""
from typing import Sequence, Union

from alembic import context, op
import sqlalchemy as sa


revision: str = '20260729_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_names(bind, table_name: str) -> set[str]:
    return {column["name"] for column in sa.inspect(bind).get_columns(table_name)}


def _index_names(bind, table_name: str) -> set[str]:
    return {index["name"] for index in sa.inspect(bind).get_indexes(table_name)}


def _align_existing_schema(bind) -> None:
    """Align a pre-Alembic CyberPME database without deleting its data."""
    organization_columns = _column_names(bind, "organizations")
    for column_name in ("enrollment_key_hash", "scan_key_hash"):
        if column_name not in organization_columns:
            op.add_column(
                "organizations",
                sa.Column(column_name, sa.String(length=64), nullable=True),
            )

    organization_id = bind.execute(
        sa.text("SELECT id FROM organizations ORDER BY created_at LIMIT 1")
    ).scalar()
    for table_name in ("servers", "network_scans", "ssl_checks"):
        if "organization_id" not in _column_names(bind, table_name):
            op.add_column(
                table_name,
                sa.Column("organization_id", sa.Uuid(), nullable=True),
            )
            row_count = bind.execute(
                sa.text(f"SELECT COUNT(*) FROM {table_name}")
            ).scalar_one()
            if row_count and organization_id is None:
                raise RuntimeError(
                    f"Impossible de rattacher les données existantes de {table_name} "
                    "car aucune organisation n'existe."
                )
            if organization_id is not None:
                bind.execute(
                    sa.text(
                        f"UPDATE {table_name} "
                        "SET organization_id = :organization_id "
                        "WHERE organization_id IS NULL"
                    ),
                    {"organization_id": organization_id},
                )
            with op.batch_alter_table(table_name) as batch_op:
                batch_op.alter_column(
                    "organization_id",
                    existing_type=sa.Uuid(),
                    nullable=False,
                )
        index_name = f"ix_{table_name}_organization_id"
        if index_name not in _index_names(bind, table_name):
            op.create_index(index_name, table_name, ["organization_id"])

    server_constraints = {
        constraint["name"]
        for constraint in sa.inspect(bind).get_unique_constraints("servers")
        if constraint.get("name")
    }
    if "servers_hostname_key" in server_constraints:
        with op.batch_alter_table("servers") as batch_op:
            batch_op.drop_constraint("servers_hostname_key", type_="unique")
    if "uq_server_organization_hostname" not in _index_names(bind, "servers"):
        if "uq_server_organization_hostname" not in server_constraints:
            op.create_index(
                "uq_server_organization_hostname",
                "servers",
                ["organization_id", "hostname"],
                unique=True,
            )

    security_columns = _column_names(bind, "security_events")
    security_additions = {
        "handled_by_email": sa.Column(
            "handled_by_email",
            sa.String(length=254),
            nullable=True,
        ),
        "acknowledged_at": sa.Column(
            "acknowledged_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        "resolved_at": sa.Column(
            "resolved_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        "resolution_note": sa.Column(
            "resolution_note",
            sa.Text(),
            nullable=True,
        ),
    }
    for column_name, column in security_additions.items():
        if column_name not in security_columns:
            op.add_column("security_events", column)
    bind.execute(
        sa.text("UPDATE security_events SET status = 'new' WHERE status = 'active'")
    )


def upgrade() -> None:
    """Create a fresh schema or safely adopt the current pre-Alembic schema."""
    if context.is_offline_mode():
        _create_fresh_schema()
        return
    bind = op.get_bind()
    if sa.inspect(bind).has_table("organizations"):
        _align_existing_schema(bind)
        return
    _create_fresh_schema()


def _create_fresh_schema() -> None:
    """Create the immutable schema snapshot for a new CyberPME installation."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('enrollment_key_hash', sa.String(length=64), nullable=True),
    sa.Column('scan_key_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('audit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_email', sa.String(length=254), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_actor_email'), ['actor_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_target_type'), ['target_type'], unique=False)

    op.create_table('network_scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_scans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_scans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_scans_target'), ['target'], unique=False)

    op.create_table('servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'hostname', name='uq_server_organization_hostname')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_organization_id'), ['organization_id'], unique=False)

    op.create_table('ssl_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=253), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('issuer', sa.String(length=500), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('chain_valid', sa.Boolean(), nullable=False),
    sa.Column('tls_version', sa.String(length=30), nullable=True),
    sa.Column('cipher', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ssl_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ssl_checks_hostname'), ['hostname'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssl_checks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssl_checks_status'), ['status'], unique=False)

    op.create_table('user_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_by_email', sa.String(length=254), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_invitations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_invitations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_invitations_token_hash'), ['token_hash'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_organization_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('agent_credentials',
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('resource', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_resource'), ['resource'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('backup_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exists', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_age_hours', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_checks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_checks_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backup_checks_status'), ['status'], unique=False)

    op.create_table('ids_connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('connector_type', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_ids_connector_organization_name')
    )
    with op.batch_alter_table('ids_connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ids_connectors_connector_type'), ['connector_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ids_connectors_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ids_connectors_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ids_connectors_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ids_connectors_token_hash'), ['token_hash'], unique=True)

    op.create_table('metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_server_id'), ['server_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('event_key', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('rule_id', sa.String(length=80), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by_email', sa.String(length=254), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'event_key', name='uq_security_event_server_key')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_status'), ['status'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """The adoption baseline must never erase a customer's existing database."""
    raise RuntimeError(
        "La migration de référence ne peut pas être annulée automatiquement. "
        "Restaurez une sauvegarde contrôlée pour revenir avant cette version."
    )
